Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Exclude:
    - 'lib/poper/cli.rb'
